config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'shelters#index' #eventually change this to a welcome/home page

  get '/shelters', to: 'shelters#index'
  get '/shelters/new', to: 'shelters#new'
  post '/shelters', to: 'shelters#create'
  get '/shelters/:id', to: 'shelters#show'
  get '/shelters/:id/edit', to: 'shelters#edit'
  patch '/shelters/:id', to: 'shelters#update'
  delete '/shelters/:id', to: 'shelters#destroy'

  get '/shelters/:shelter_id/pets', to: 'shelters#pets_index'
  get '/shelters/:id/pets/new', to: 'pets#new'
  post '/shelters/:shelter_id/pets', to: 'pets#create'

  get '/pets', to: 'pets#index'
  get '/pets/:id', to: 'pets#show'
  get '/pets/:id/edit', to: 'pets#edit'
  patch '/pets/:id', to: 'pets#update'
  delete '/pets/:id', to: 'pets#destroy'

  get '/shelters/:id/reviews/new', to: 'reviews#new'
  post '/shelters/:id/reviews', to: 'reviews#create'
  get '/reviews/:id/edit', to: 'reviews#edit'
  patch '/reviews/:id', to: 'reviews#update'
  delete '/reviews/:id', to: 'reviews#destroy'

  post 'pets/:id/favorites', to: 'favorites#create'
  get '/favorites', to: 'favorites#index'
  delete '/favorites/:id', to: 'favorites#destroy'
  delete '/favorites', to: 'favorites#destroy_all'

  get 'favorites/application', to: 'apps#new'
  get '/applications', to: 'apps#create'
  post '/applications', to: 'apps#create'
  get 'applications/:id', to: 'apps#show'
  get '/pets/:id/applications', to: 'apps#index'
  patch "/applications/:id/:pet_id/:pet_status", to: 'apps_pet#update_status'
end

app/models/app.rb
class App < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :address
  validates_presence_of :city
  validates_presence_of :state
  validates_presence_of :zip
  validates_presence_of :phone_number
  validates_presence_of :description

  has_many :apps_pets
  has_many :pets, through: :apps_pets
end

app/views/apps/index.html.erb
  <h2>Applications for <%= link_to @pet.name, "/pets/#{@pet.id}" %></h2>

<section>
 <h3>Names of Applicants:</h3>

 <% unless @pet.apps.empty? %>
   <% @pet.apps.each do |application| %>
     <p><%= link_to application.name, "/applications/#{application.id}" %></p>
   <% end %>
 <% else %>
   <p>No applications for this pet exist.</p>
 <% end %>
</section>

app/views/apps/new.html.erb
<div class="adpotion-application">
  <h1>Application to Adopt Pets</h1>
  <div class="new_application_info">
    <ol>
      <%= form_tag('/applications',  method: :post) do %>
        <% @favorites.pet_objects.each do |pet| %>
          <%= pet.name %>
          <%= check_box_tag("pet_ids[]", pet.id) %><br>
        <% end %>
        <li> <%= label_tag "Name" %></li>
        <%= text_field_tag :name %><br>
        <li><%= label_tag "Address" %></li>
        <%= text_field_tag :address %><br>
        <li><%= label_tag "City" %></li>
        <%= text_field_tag :city %><br>
        <li><%= label_tag "State" %></li>
        <%= text_field_tag :state%><br>
        <li><%= label_tag "Zipcode" %></li>
        <%= text_field_tag :zip %><br>
        <li><%= label_tag "Phone Number" %></li>
        <%= text_field_tag :phone_number %><br>
        <li><%= label_tag "Description" %></li>
        <%= text_field_tag :description %><br>
        <a><%= submit_tag 'Submit Application' %></a>
      <% end %>
    </ol>
  </div>
</div>

app/views/apps/show.html.erb
<h2>Application Details</h2>

<section>
  <p>Name: <%= link_to @application.name, "/applications/#{@application.id}" %></p>
  <p>Address: <%= @application.address %></p>
  <p>City: <%= @application.city %></p>
  <p>State: <%= @application.state %></p>
  <p>Zip: <%= @application.zip %></p>
  <p>Phone Number: <%= @application.phone_number %></p>
  <p>Description: <%= @application.description %></p>
</section>
<section>
  <h3>Pets You Have Applied For</h3>
  <% @application.pets.each do |pet|%>
  <%= link_to pet.name, "/pets/#{pet.id}" %>
  <section id="pet-links-<%= pet.id %>">
    <% if pet.adoptable? %>
      <%= link_to "Approve application for pet: #{pet.name}", "/applications/#{@application.id}/#{pet.id}/pending", method: :patch %>
    <% else %>
      <%= link_to "Revoke application for: #{pet.name}", "/applications/#{@application.id}/#{pet.id}/adoptable", method: :patch %>
    <% end %>
  </section>
  <% end %>
</section>